# Generated by Django 5.1 on 2024-09-03 17:01

import django.db.models.deletion
import msg.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('email', models.EmailField(max_length=256, unique=True, validators=[msg.utils.EmailDomenValidator()], verbose_name='Почта')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('provider', models.CharField(choices=[('YANDEX', 'yandex.ru'), ('MAILRU', 'mail.ru'), ('GMAIL', 'gmail.com')], default='YANDEX', verbose_name='Провайдер почты')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почты',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('email_from', models.CharField(null=True, verbose_name='Отправитель')),
                ('title', models.CharField(null=True, verbose_name='Тема сообщения')),
                ('dispatch_date', models.DateField(verbose_name='Дата отправки')),
                ('receipt_date', models.DateField(verbose_name='Дата получения')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('msg_read', models.BooleanField(default=False, verbose_name='Письмо прочитано да/нет')),
                ('files', models.JSONField(blank=True, null=True, verbose_name='Прикрепленные файлы')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_data', to='msg.email', verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Данные из письма',
                'verbose_name_plural': 'Данные из писем',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('file', models.FileField(upload_to=msg.utils.mail_directory_path, verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_files', to='msg.messagedata', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('created_at',),
            },
        ),
    ]
