# Generated by Django 5.1 on 2024-08-29 17:26

import msg.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=256, unique=True, validators=[msg.utils.EmailDomenValidator()], verbose_name='Почта'),
        ),
    ]
