# Generated by Django 5.1 on 2024-09-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_data', to='msg.email', verbose_name='Отправитель'),
        ),
    ]
