# Generated by Django 5.1 on 2024-09-02 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_messagedata_email_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='uid',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_data', to='msg.email', verbose_name='Почта'),
        ),
    ]
