# Generated by Django 5.1 on 2024-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_messagedata_uid_alter_messagedata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='title',
            field=models.CharField(null=True, verbose_name='Тема сообщения'),
        ),
    ]
