# Generated by Django 5.1 on 2024-09-03 14:17

import django.db.models.deletion
import msg.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0006_alter_messagedata_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('file', models.FileField(upload_to=msg.utils.mail_directory_path, verbose_name='Контракт')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_files', to='msg.messagedata', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('created_at',),
            },
        ),
    ]
